site_name: STROMA Documentation guide
theme: 
  name: material 
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
nav:
  - About STROMA : "index.md"
  - STROMA Archiecture : "Medallion-Archiecture.md" 
  - SqlMesh Setup & Config: "Sqlmeshworkflow.md"