name: SQLMesh Deployment to Dev

on:
  workflow_call:
    inputs:
     environment:
        required: false
        type: string
     vm-image:
        required: true
        type: string

jobs:
  Deploy-SQLMesh:
    runs-on: ${{ inputs.vm-image }}
    environment: ${{ inputs.environment}}

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # Step 3: Install SQLMesh with `databricks` dependencies
      - name: Install SQLMesh
        run: |
          pip install sqlmesh[databricks]

      # Step 4: Set up Databricks environment variables (using GitHub Secrets)
      - name: Set up Databricks Environment Variables
        run: |
          echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}" >> $GITHUB_ENV
          echo "DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}" >> $GITHUB_ENV
          echo "SQLMESH_DEFAULT_GATEWAY=databricks" >> $GITHUB_ENV

      # Step 5: Run `sqlmesh plan` and `sqlmesh apply` for the environment
      - name: Run SQLMesh Plan & Apply
        run: |
          sqlmesh plan
          sqlmesh apply

      # Step 6: Run SQLMesh models in the environment
      - name: Run SQLMesh Models
        run: |
          sqlmesh run --environment ${{ inputs.environment }}

      # Step 7: Notify results
      - name: Notify Deployment Status
        run: |
          echo "Deployment to ${{ inputs.environment }} completed successfully!"

