name: SQLMesh Deployment

on:
  workflow_call:
    inputs:
     environment:
        required: false
        type: string
     vm-image:
        required: true
        type: string

jobs:
  Deploy-SQLMesh:
    runs-on: ${{ inputs.vm-image }}
    permissions:
      contents: write
      issues: write
      checks: write
      pull-requests: write
    environment: ${{ inputs.environment}}
    env:
      DEFAULT_GATEWAY: "databricks"
      ENABLED_GATEWAYS: "databricks"
      STATE_SCHEMA: "stroma"
      DATABRICKS_ACCESS_TOKEN: ${{ secrets.DATABRICKS_ACCESS_TOKEN }}
      DATABRICKS_SERVER_HOSTNAME:  ${{ secrets.DATABRICKS_SERVER_HOSTNAME }}
      DATABRICKS_HTTP_PATH:  ${{ secrets.DATABRICKS_HTTP_PATH }}
      DATABRICKS_CATALOG:  ${{ secrets.DATABRICKS_CATALOG }}
      DATABRICKS_CATALOG_SOURCE:  ${{ secrets.DATABRICKS_CATALOG_SOURCE }}
      DATABRICKS_SCHEMA_BASE: ${{ secrets.DATABRICKS_SCHEMA }}
      DATABRICKS_SCHEMA_VOCAB: ${{ secrets.DATABRICKS_SCHEMA }}
      AZURE_SQL_SERVER_STATE_HOST: ${{ secrets.AZURE_SQL_SERVER_STATE_HOST }}
      AZURE_SQL_SERVER_STATE_PORT: ${{ secrets.AZURE_SQL_SERVER_STATE_PORT }}
      AZURE_SQL_STATE_DATABASE: ${{ secrets.AZURE_SQL_STATE_DATABASE }}
      AZURE_SQL_SERVER_STATE_USER: ${{ secrets.AZURE_SQL_SERVER_STATE_USER }}
      AZURE_SQL_SERVER_STATE_PASSWORD: ${{ secrets.AZURE_SQL_SERVER_STATE_PASSWORD }}

    steps:
      # Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Install SQLMesh
      - name: Install SQLMesh
        run: |
          pip install sqlmesh[databricks,postgres,github,azuresql,mssql]==0.170.0
          pip install python-dotenv

      # Run `sqlmesh plan` and `sqlmesh apply` for the environment
      - name: Run SQLMesh Plan & Apply
        run: |
          sqlmesh_cicd -p ${{ github.workspace }}/stroma/ github --token ${{ secrets.GITHUB_TOKEN }} run-all
