name: SQLMesh Deployment

on:
  workflow_call:
    inputs:
     environment:
        required: false
        type: string
     vm-image:
        required: true
        type: string

jobs:
  Deploy-SQLMesh:
    runs-on: ${{ inputs.vm-image }}
    environment: ${{ inputs.environment}}
    env:
      SQLMESH__DEFAULT_GATEWAY: "databricks"
      SQLMESH__ENABLED_GATEWAY: "databricks"
      SQLMESH__STATE_SCHEMA: "stroma"
      SQLMESH__DUCKDB_DATABASE: ""
      SQLMESH__DUCKDB_STATE_DATABASE: ""
      SQLMESH__DATABRICKS_CONCURRENT_TASKS:  '8'
      SQLMESH__DATABRICKS_ACCESS_TOKEN: ${{ secrets.DATABRICKS_ACCESS_TOKEN }}
      DATABRICKS_SERVER_HOSTNAME:  ${{ secrets.DATABRICKS_SERVER_HOSTNAME }}
      SQLMESH__DATABRICKS_HTTP_PATH:  ${{ secrets.DATABRICKS_HTTP_PATH }}
      SQLMESH__DATABRICKS_CATALOG:  ${{ secrets.DATABRICKS_CATALOG }}
      SQLMESH__DATABRICKS_CATALOG_SOURCE:  ${{ secrets.DATABRICKS_CATALOG_SOURCE }}
      SQLMESH__DATABRICKS_STATE_DB_USER: ${{ secrets.DATABRICKS_STATE_DB_USER }}
      SQLMESH__DATABRICKS_STATE_DB_PASSWORD: ${{ secrets.DATABRICKS_STATE_DB_PASSWORD }}
      SQLMESH__DATABRICKS_SCHEMA_BASE: ${{ secrets.DATABRICKS_SCHEMA }}
      SQLMESH__DATABRICKS_SCHEMA_VOCAB: ${{ secrets.DATABRICKS_SCHEMA }}
      SQLMESH__DATABRICKS_STATE_DB_HOST: ${{ secrets.DATABRICKS_STATE_DB_HOST }}
      SQLMESH__DATABRICKS_STATE_DB_PORT: ${{ secrets.DATABRICKS_STATE_DB_PORT }}
      SQLMESH__DATABRICKS_STATE_DB_DATABASE: ${{ secrets.DATABRICKS_STATE_DB_DATABASE }}

    steps:
      # Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Install SQLMesh
      - name: Install SQLMesh
        run: |
          pip install sqlmesh[databricks,postgres,github]
          pip install python-dotenv

      # Run `sqlmesh plan` and `sqlmesh apply` for the environment
      - name: Run SQLMesh Plan & Apply
        run: |
          sqlmesh_cicd -p ${{ github.workspace }}/stroma/ github --token ${{ secrets.GITHUB_TOKEN }} run-all